/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entity;

import java.util.LinkedList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Yassine
 */

public class Formulaire extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Participant
     */
    public Formulaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JRBMme = new javax.swing.JRadioButton();
        JRBMlle = new javax.swing.JRadioButton();
        JRBMonsieur = new javax.swing.JRadioButton();
        JBEnregistrer = new javax.swing.JButton();
        JBLister = new javax.swing.JButton();
        JBSupprimer = new javax.swing.JButton();
        JTFID = new javax.swing.JTextField();
        JTFNom = new javax.swing.JTextField();
        JTFPrenom = new javax.swing.JTextField();
        JTFemail = new javax.swing.JTextField();
        JSPINAge = new javax.swing.JSpinner();
        JCProfession = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gestion des participants");
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ajouter un nouveau participant");

        jLabel2.setText("ID");

        jLabel3.setText("Nom");

        jLabel4.setText("Prénom");

        jLabel5.setText("Age");

        jLabel6.setText("E-mail");

        jLabel7.setText("Profession");

        buttonGroup.add(JRBMme);
        JRBMme.setText("Mme");

        buttonGroup.add(JRBMlle);
        JRBMlle.setText("Mlle");
        JRBMlle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBMlleActionPerformed(evt);
            }
        });

        buttonGroup.add(JRBMonsieur);
        JRBMonsieur.setText("Monsieur");

        JBEnregistrer.setText("Enregistrer");
        JBEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEnregistrerActionPerformed(evt);
            }
        });

        JBLister.setText("Lister");
        JBLister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBListerActionPerformed(evt);
            }
        });

        JBSupprimer.setText("Supprimer");
        JBSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerActionPerformed(evt);
            }
        });

        JCProfession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Professeur", "Etudiant" }));

        JTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Prénom", "Age", "Email", "Profession", "Civilité"
            }
        ));
        JTABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JRBMme)
                                .addGap(49, 49, 49)
                                .addComponent(JRBMlle)
                                .addGap(42, 42, 42)
                                .addComponent(JRBMonsieur))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBEnregistrer)
                                .addGap(27, 27, 27)
                                .addComponent(JBLister))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(JBSupprimer))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JTFemail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JSPINAge, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFNom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCProfession, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTFNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTFPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JSPINAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(JTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JCProfession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRBMme)
                            .addComponent(JRBMlle)
                            .addComponent(JRBMonsieur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBEnregistrer)
                            .addComponent(JBLister))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBSupprimer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JBEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEnregistrerActionPerformed
    int id = Integer.parseInt(JTFID.getText());
       String Nom = JTFNom.getText();
       String Prenom = JTFPrenom.getText();
       int age = (int) JSPINAge.getValue();
       String email = JTFemail.getText();
       String profession = JCProfession.getSelectedItem().toString();

       String civilite = null;
       if(JRBMme.isSelected()){
           civilite = "Mme"; 
       }
       if(JRBMlle.isSelected()){
           civilite = "Mlle";
       }
       if(JRBMonsieur.isSelected()){
           civilite = "Monsieur";
       }
       
       Participant p = new Participant(id, Nom, Prenom, age, email, profession, civilite);
       Participant.listeParticipant.add(p);
       
       DefaultTableModel tbl = (DefaultTableModel) JTABLE.getModel();
       tbl.addRow(new Object[]{
           p.ID,p.Nom,p.Prenom,p.age,p.Email,p.Profession,p.Civilite,});

       for(int i=0;i<Participant.listeParticipant.size();i++){
        System.out.println("linked list add: "+ Participant.listeParticipant.get(i));}
       
       
        
    }//GEN-LAST:event_JBEnregistrerActionPerformed

    private void JRBMlleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBMlleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBMlleActionPerformed

    private void JBSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerActionPerformed
        // TODO add your handling code here:             
        DefaultTableModel tbl = (DefaultTableModel) JTABLE.getModel();
             
        tbl.removeRow(JTABLE.getSelectedRow());
  
        JTFID.setText("");
        JTFNom.setText("");
        JTFPrenom.setText("");
        JSPINAge.setValue(0);
        JTFemail.setText("");
        JCProfession.setSelectedIndex(0);
        JRBMme.setSelected(false);
        JRBMlle.setSelected(false);
        JRBMonsieur.setSelected(false);
        
        Participant.listeParticipant.remove();
        for(int i=0;i<Participant.listeParticipant.size();i++){
        System.out.println("linked list remove: "+ Participant.listeParticipant.get(i));}
        JOptionPane.showMessageDialog(this, "Row removed successfully");
    }//GEN-LAST:event_JBSupprimerActionPerformed

    private void JTABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLEMouseClicked
        int row = JTABLE.getSelectedRow(); 
        
        DefaultTableModel model = (DefaultTableModel)JTABLE.getModel();

        
        JTFID.setText(model.getValueAt(row,0).toString());
        JTFNom.setText(model.getValueAt(row,1).toString());
        JTFPrenom.setText(model.getValueAt(row,2).toString());
        JSPINAge.setValue((int)model.getValueAt(row,3));
        JTFemail.setText(model.getValueAt(row, 4).toString());
        String profession = JTABLE.getValueAt(row,5).toString();
        String civilite = JTABLE.getValueAt(row, 6).toString();
            
 
        switch(profession){
            case "Administrateur":
                JCProfession.setSelectedIndex(0);
        break;
            case "Professeur":
                JCProfession.setSelectedIndex(1);
        break;
            case "Etudiant":
                JCProfession.setSelectedIndex(2);
        break;
        }
        if(civilite.equals("Mme")){
                JRBMme.setSelected(true);
            }
            if(civilite.equals("Mlle")){
                JRBMlle.setSelected(true);
            }
            if(civilite.equals("Monsieur")){
                JRBMonsieur.setSelected(true);
            }
            
       
    }//GEN-LAST:event_JTABLEMouseClicked

    private void JBListerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBListerActionPerformed
        // TODO add your handling code here:
        
        //add info to linkedList 
         Participant.listeParticipant.add(new Participant(1, "Der", "Yassine",17, "yy@dd", "Etudiant", "Monsieur"));
         Participant.listeParticipant.add(new Participant(234, "AZER", "TY", 22, "ea@aa", "Professeur", "Mme"));

          Vector<String> VCols = new Vector<String> ();
          VCols.add("id");
          VCols.add("nom");
          VCols.add("Prenom");
          VCols.add("age");
          VCols.add("email");
          VCols.add("profession");
          VCols.add("civilite");

          Vector<Object> VRows = new Vector<Object> ();
          
          Vector<Vector<Object>> VData = new Vector<Vector<Object>>();

        for(Participant pa : Participant.listeParticipant){
            
            VRows =  new Vector<Object> ();
            VRows.add(pa.ID);
            VRows.add(pa.Nom);
            VRows.add(pa.Prenom);
            VRows.add(pa.age);
            VRows.add(pa.Email);
            VRows.add(pa.Profession);
            VRows.add(pa.Civilite);
            VData.add(VRows);
        }  

        DefaultTableModel Dynamictbl = new DefaultTableModel(VData, VCols);
        JTABLE.setModel(Dynamictbl);
    }//GEN-LAST:event_JBListerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEnregistrer;
    private javax.swing.JButton JBLister;
    private javax.swing.JButton JBSupprimer;
    private javax.swing.JComboBox<String> JCProfession;
    private javax.swing.JRadioButton JRBMlle;
    private javax.swing.JRadioButton JRBMme;
    private javax.swing.JRadioButton JRBMonsieur;
    private javax.swing.JSpinner JSPINAge;
    private javax.swing.JTable JTABLE;
    private javax.swing.JTextField JTFID;
    private javax.swing.JTextField JTFNom;
    private javax.swing.JTextField JTFPrenom;
    private javax.swing.JTextField JTFemail;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
